import os
os.environ["CUBLAS_WORKSPACE_CONFIG"] = ":4096:8"

import torch
import torch.nn.functional as F

from codex_loops import generative_encoding, generative_decoding
from payload_converter import string2bits, bits2string

torch.use_deterministic_algorithms(True)
torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False


if __name__ == "__main__":

    # ================================================================
    # Parameters
    # ================================================================
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Running on: {device}")
    dtype = torch.bfloat16
    model_nickname = "gemma"  # Short name of the LLM ("llama", "mistral", "qwen", "gemma")
    temperature = 0.5
    top_k = 10  # Number of highest-probability tokens to keep
    tokens_limit = 500  # Maximum number of tokens generated by the LLM to answer the prompt
    length_header_bits = 16  # Amount of additioanl bits used in the payload to encode the length of the message
    seed = 6  # Random seed for reproducibility


    # ================================================================
    # Malicious payload
    # ================================================================
    payload_string = "sk-9f3Kx7LmQ2vB8pR4tY6wZ1aC0dE5hJ8nU3iX"  # Dummy API key
    payload_bits = string2bits(payload_string=payload_string)
    print("\n" + "="*64)
    print(f"Payload (string): {payload_string} ({len(payload_string)} characters)")
    print(f"Payload (binary): {''.join(map(str, payload_bits))} ({len(payload_bits)} bits)")
    print("="*64 + "\n")


    # ================================================================
    # Cover task
    # ================================================================
    prompt = "Explain why gradient descent converges."


    # ================================================================
    # Encoding phase
    # ================================================================
    generated_text = generative_encoding(
        payload_bits=payload_bits,
        prompt=prompt,
        seed=seed,
        model_nickname=model_nickname,
        top_k=top_k,
        temperature=temperature,
        length_header_bits=length_header_bits,
        tokens_limit=tokens_limit,
        dtype=dtype,
        device=device
    )

    # ================================================================
    # Decoding phase
    # ================================================================
    decoded_payload_bits = generative_decoding(
        generated_text=generated_text,
        prompt=prompt,
        seed=seed,
        model_nickname=model_nickname,
        top_k=top_k,
        temperature=temperature,
        length_header_bits=length_header_bits,
        dtype=dtype,
        device=device
    )

    # ================================================================
    # Verify payload match
    # ================================================================
    print("\n" + "="*64)

    assert len(decoded_payload_bits) == len(payload_bits), (
        f"Length mismatch: decoded {len(decoded_payload_bits)} bits, expected {len(payload_bits)}."
    )

    match = decoded_payload_bits == payload_bits[:len(decoded_payload_bits)]

    print(f"Encoded bits: {payload_bits}")
    print(f"Decoded bits: {decoded_payload_bits}")

    if match:
        print("✓ Perfect bit-for-bit match!")
    else:
        nb_errors = sum(1 for a, b in zip(payload_bits, decoded_payload_bits) if a != b)
        print(f"✗ Mismatch: {nb_errors} bits differ out of {len(decoded_payload_bits)}.")


    # ================================================================
    # Convert the payload from bit representation to string representation
    # ================================================================
    print("\n" + "="*64)
    try:
        decoded_payload_string = bits2string(payload_bits=decoded_payload_bits)
        print(f"Encoded message: {payload_string}")
        print(f"Decoded message: '{decoded_payload_string}'")
        if decoded_payload_string == payload_string:
            print("✓ Perfect message match!")
    except Exception as e:
        print(f"✗ Error decoding: {e}")

